repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        types: [ file ]
        files: \.(ts)$
        args: [--maxkb=100]
        exclude: '^yarn\.lock$'
      - id: check-json
        exclude: '^tsconfig.run.json$'
      - id: check-merge-conflict
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-cyclo
        exclude: "^internal/common/logger/zerolog.go$"
        args: [-over=18]
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
      - id: go-critic
      - id: go-mod-tidy
  - repo: local
    hooks:
      - id: go build
        name: go build
        entry: bash -c 'make build'
        pass_filenames: false
        language: system
      - id: clean
        name: clean
        entry: bash -c 'make clean'
        pass_filenames: false
        language: system
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-conventional' ]
